
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.morebosses.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.morebosses.item.WoodriteIngotItem;
import net.mcreator.morebosses.item.WitheredBoneItem;
import net.mcreator.morebosses.item.WitherRingItem;
import net.mcreator.morebosses.item.TheLifeEnderItem;
import net.mcreator.morebosses.item.TankOfFuryItem;
import net.mcreator.morebosses.item.StoneCuirlassItem;
import net.mcreator.morebosses.item.ShrimpDeathItem;
import net.mcreator.morebosses.item.ShieldBeaterItem;
import net.mcreator.morebosses.item.RobotGloveItem;
import net.mcreator.morebosses.item.RingItem;
import net.mcreator.morebosses.item.RawShrimpItem;
import net.mcreator.morebosses.item.RawMagmaItem;
import net.mcreator.morebosses.item.RawMagmaCreamItem;
import net.mcreator.morebosses.item.PotWithFlourItem;
import net.mcreator.morebosses.item.PotItem;
import net.mcreator.morebosses.item.PoisonRingItem;
import net.mcreator.morebosses.item.PipeWrenchItem;
import net.mcreator.morebosses.item.OxidationDustItem;
import net.mcreator.morebosses.item.OpalItem;
import net.mcreator.morebosses.item.OldSteelSmithingUpgradeItem;
import net.mcreator.morebosses.item.OldSteelIngotItem;
import net.mcreator.morebosses.item.OldEyeItem;
import net.mcreator.morebosses.item.NetheriteScimitarItem;
import net.mcreator.morebosses.item.NetheriteLongSwordItem;
import net.mcreator.morebosses.item.NetherBricksStickItem;
import net.mcreator.morebosses.item.MotherboardItem;
import net.mcreator.morebosses.item.MonstrosityEyeItem;
import net.mcreator.morebosses.item.MacabreScytheItem;
import net.mcreator.morebosses.item.MONSTROUSFOOTWEARItem;
import net.mcreator.morebosses.item.MMAGloveItem;
import net.mcreator.morebosses.item.MMAEyeItem;
import net.mcreator.morebosses.item.LushEyeItem;
import net.mcreator.morebosses.item.JungleEssenceItem;
import net.mcreator.morebosses.item.HellishTungstenIngotItem;
import net.mcreator.morebosses.item.GreenMagmaItem;
import net.mcreator.morebosses.item.GreenMagmaCreamItem;
import net.mcreator.morebosses.item.GongStickItem;
import net.mcreator.morebosses.item.GeradorDeWavesItem;
import net.mcreator.morebosses.item.GearItem;
import net.mcreator.morebosses.item.FuseItem;
import net.mcreator.morebosses.item.FriedEggItem;
import net.mcreator.morebosses.item.FriedChayoteItem;
import net.mcreator.morebosses.item.FlourItem;
import net.mcreator.morebosses.item.FleshItem;
import net.mcreator.morebosses.item.FireRingItem;
import net.mcreator.morebosses.item.EmptyTankItem;
import net.mcreator.morebosses.item.DiamondedBlomiBerryItem;
import net.mcreator.morebosses.item.CuirlassSmithingUpgradeItem;
import net.mcreator.morebosses.item.CuirlassGloveItem;
import net.mcreator.morebosses.item.CuirlassArmorItem;
import net.mcreator.morebosses.item.CopperWiresItem;
import net.mcreator.morebosses.item.CopperSoupItem;
import net.mcreator.morebosses.item.CopperHammerItem;
import net.mcreator.morebosses.item.CopperGloveItem;
import net.mcreator.morebosses.item.CopperDiscItem;
import net.mcreator.morebosses.item.CookedShrimpItem;
import net.mcreator.morebosses.item.BrokenSwordItem;
import net.mcreator.morebosses.item.BrokenIdolItem;
import net.mcreator.morebosses.item.BossRemoverItem;
import net.mcreator.morebosses.item.BoneCarverItem;
import net.mcreator.morebosses.item.BoiledEggItem;
import net.mcreator.morebosses.item.BobItem;
import net.mcreator.morebosses.item.BlomiBerrySeedsItem;
import net.mcreator.morebosses.item.BlomiBerryItem;
import net.mcreator.morebosses.item.BasalticShieldItem;
import net.mcreator.morebosses.item.BasalticShardItem;
import net.mcreator.morebosses.item.ArmagedomItem;
import net.mcreator.morebosses.block.display.GongDisplayItem;
import net.mcreator.morebosses.MorebossesMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class MorebossesModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MorebossesMod.MODID);
	public static final RegistryObject<Item> GREEN_MAGMA_BLOCK = block(MorebossesModBlocks.GREEN_MAGMA_BLOCK);
	public static final RegistryObject<Item> GREEN_MAGMA_CREAM = REGISTRY.register("green_magma_cream", () -> new GreenMagmaCreamItem());
	public static final RegistryObject<Item> GREEN_MAGMA_BUCKET = REGISTRY.register("green_magma_bucket", () -> new GreenMagmaItem());
	public static final RegistryObject<Item> RAW_MAGMA_BUCKET = REGISTRY.register("raw_magma_bucket", () -> new RawMagmaItem());
	public static final RegistryObject<Item> COPPER_MONSTROSITY_SPAWN_EGG = REGISTRY.register("copper_monstrosity_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.COPPER_MONSTROSITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MAXOLOT_SPAWN_EGG = REGISTRY.register("maxolot_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.MAXOLOT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GERADOR_DE_WAVES = REGISTRY.register("gerador_de_waves", () -> new GeradorDeWavesItem());
	public static final RegistryObject<Item> DRY_BONES_SPAWN_EGG = REGISTRY.register("dry_bones_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.DRY_BONES, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> STONE_CUIRLASS = REGISTRY.register("stone_cuirlass", () -> new StoneCuirlassItem());
	public static final RegistryObject<Item> TANK_OF_FURY = REGISTRY.register("tank_of_fury", () -> new TankOfFuryItem());
	public static final RegistryObject<Item> EMPTY_TANK = REGISTRY.register("empty_tank", () -> new EmptyTankItem());
	public static final RegistryObject<Item> CUIRLASS_ARMOR_HELMET = REGISTRY.register("cuirlass_armor_helmet", () -> new CuirlassArmorItem.Helmet());
	public static final RegistryObject<Item> CUIRLASS_ARMOR_CHESTPLATE = REGISTRY.register("cuirlass_armor_chestplate", () -> new CuirlassArmorItem.Chestplate());
	public static final RegistryObject<Item> CUIRLASS_ARMOR_LEGGINGS = REGISTRY.register("cuirlass_armor_leggings", () -> new CuirlassArmorItem.Leggings());
	public static final RegistryObject<Item> CUIRLASS_ARMOR_BOOTS = REGISTRY.register("cuirlass_armor_boots", () -> new CuirlassArmorItem.Boots());
	public static final RegistryObject<Item> CUIRLASS_SMITHING_UPGRADE = REGISTRY.register("cuirlass_smithing_upgrade", () -> new CuirlassSmithingUpgradeItem());
	public static final RegistryObject<Item> SHIELD_BEATER = REGISTRY.register("shield_beater", () -> new ShieldBeaterItem());
	public static final RegistryObject<Item> MINILOTL_SPAWN_EGG = REGISTRY.register("minilotl_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.MINILOTL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MONSTROUSFOOTWEAR_BOOTS = REGISTRY.register("monstrousfootwear_boots", () -> new MONSTROUSFOOTWEARItem.Boots());
	public static final RegistryObject<Item> NETHER_BRICKS_STICK = REGISTRY.register("nether_bricks_stick", () -> new NetherBricksStickItem());
	public static final RegistryObject<Item> GONG_STICK = REGISTRY.register("gong_stick", () -> new GongStickItem());
	public static final RegistryObject<Item> GONG = REGISTRY.register(MorebossesModBlocks.GONG.getId().getPath(), () -> new GongDisplayItem(MorebossesModBlocks.GONG.get(), new Item.Properties()));
	public static final RegistryObject<Item> POLISHED_CRACKED_BLACKSTONE_BLOCK = block(MorebossesModBlocks.POLISHED_CRACKED_BLACKSTONE_BLOCK);
	public static final RegistryObject<Item> WITHERED_BONE_BLOCK = block(MorebossesModBlocks.WITHERED_BONE_BLOCK);
	public static final RegistryObject<Item> WITHERED_BONE = REGISTRY.register("withered_bone", () -> new WitheredBoneItem());
	public static final RegistryObject<Item> CARVED_WITHERED_BONE_BLOCK = block(MorebossesModBlocks.CARVED_WITHERED_BONE_BLOCK);
	public static final RegistryObject<Item> CARVED_BONE_BLOCK = block(MorebossesModBlocks.CARVED_BONE_BLOCK);
	public static final RegistryObject<Item> RAW_MAGMA_BLOCK = block(MorebossesModBlocks.RAW_MAGMA_BLOCK);
	public static final RegistryObject<Item> SEAT = block(MorebossesModBlocks.SEAT);
	public static final RegistryObject<Item> SOUL_DIONAEA_SPAWN_EGG = REGISTRY.register("soul_dionaea_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.SOUL_DIONAEA, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SOUL_LIGHT = block(MorebossesModBlocks.SOUL_LIGHT);
	public static final RegistryObject<Item> BLUE_SOUL_LIGHT = block(MorebossesModBlocks.BLUE_SOUL_LIGHT);
	public static final RegistryObject<Item> RAW_MAGMA_CREAM = REGISTRY.register("raw_magma_cream", () -> new RawMagmaCreamItem());
	public static final RegistryObject<Item> BONE_CARVER = REGISTRY.register("bone_carver", () -> new BoneCarverItem());
	public static final RegistryObject<Item> FRIED_CHAYOTE = REGISTRY.register("fried_chayote", () -> new FriedChayoteItem());
	public static final RegistryObject<Item> BOILED_EGG = REGISTRY.register("boiled_egg", () -> new BoiledEggItem());
	public static final RegistryObject<Item> FRIED_EGG = REGISTRY.register("fried_egg", () -> new FriedEggItem());
	public static final RegistryObject<Item> CHAYOTE = block(MorebossesModBlocks.CHAYOTE);
	public static final RegistryObject<Item> POT = REGISTRY.register("pot", () -> new PotItem());
	public static final RegistryObject<Item> BEGGAR_WOLF_SPAWN_EGG = REGISTRY.register("beggar_wolf_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.BEGGAR_WOLF, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> FLOUR = REGISTRY.register("flour", () -> new FlourItem());
	public static final RegistryObject<Item> POT_WITH_FLOUR = REGISTRY.register("pot_with_flour", () -> new PotWithFlourItem());
	public static final RegistryObject<Item> FLESH = REGISTRY.register("flesh", () -> new FleshItem());
	public static final RegistryObject<Item> ENGINEER_SPAWN_EGG = REGISTRY.register("engineer_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.ENGINEER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BRUTE_ENGINEER_SPAWN_EGG = REGISTRY.register("brute_engineer_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.BRUTE_ENGINEER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TURRET_SPAWN_EGG = REGISTRY.register("turret_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.TURRET, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TALL_ENGINEER_SPAWN_EGG = REGISTRY.register("tall_engineer_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.TALL_ENGINEER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> OIL_ENGINEER_SPAWN_EGG = REGISTRY.register("oil_engineer_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.OIL_ENGINEER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PIPE_WRENCH = REGISTRY.register("pipe_wrench", () -> new PipeWrenchItem());
	public static final RegistryObject<Item> MACABRE_SCYTHE = REGISTRY.register("macabre_scythe", () -> new MacabreScytheItem());
	public static final RegistryObject<Item> MONSTROSITY_EYE = REGISTRY.register("monstrosity_eye", () -> new MonstrosityEyeItem());
	public static final RegistryObject<Item> COPPER_FALL = block(MorebossesModBlocks.COPPER_FALL);
	public static final RegistryObject<Item> COPPER_LAVA = block(MorebossesModBlocks.COPPER_LAVA);
	public static final RegistryObject<Item> COPPER_BOOOM = block(MorebossesModBlocks.COPPER_BOOOM);
	public static final RegistryObject<Item> MMA_EYE = REGISTRY.register("mma_eye", () -> new MMAEyeItem());
	public static final RegistryObject<Item> GEAR = REGISTRY.register("gear", () -> new GearItem());
	public static final RegistryObject<Item> INDESTRUCTIBLE_BLOCK = block(MorebossesModBlocks.INDESTRUCTIBLE_BLOCK);
	public static final RegistryObject<Item> COPPER_WIRES = REGISTRY.register("copper_wires", () -> new CopperWiresItem());
	public static final RegistryObject<Item> FUSE = REGISTRY.register("fuse", () -> new FuseItem());
	public static final RegistryObject<Item> MOTHERBOARD = REGISTRY.register("motherboard", () -> new MotherboardItem());
	public static final RegistryObject<Item> COPPER_HAMMER = REGISTRY.register("copper_hammer", () -> new CopperHammerItem());
	public static final RegistryObject<Item> COPPER_SOUP = REGISTRY.register("copper_soup", () -> new CopperSoupItem());
	public static final RegistryObject<Item> OXIDATION_DUST = REGISTRY.register("oxidation_dust", () -> new OxidationDustItem());
	public static final RegistryObject<Item> COPPER_GRATES = block(MorebossesModBlocks.COPPER_GRATES);
	public static final RegistryObject<Item> COPPER_PRESSURE_PLATE = block(MorebossesModBlocks.COPPER_PRESSURE_PLATE);
	public static final RegistryObject<Item> COPPER_STRUCTURE_DETECT = block(MorebossesModBlocks.COPPER_STRUCTURE_DETECT);
	public static final RegistryObject<Item> COPPER_GRABLER_SPAWN_EGG = REGISTRY.register("copper_grabler_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.COPPER_GRABLER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> NETHERITE_SCIMITAR = REGISTRY.register("netherite_scimitar", () -> new NetheriteScimitarItem());
	public static final RegistryObject<Item> CUIRLASS_GLOVE = REGISTRY.register("cuirlass_glove", () -> new CuirlassGloveItem());
	public static final RegistryObject<Item> MEGA_FORGE = block(MorebossesModBlocks.MEGA_FORGE);
	public static final RegistryObject<Item> ROBOT_GLOVE = REGISTRY.register("robot_glove", () -> new RobotGloveItem());
	public static final RegistryObject<Item> ROBOT_WHALE_SPAWN_EGG = REGISTRY.register("robot_whale_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.ROBOT_WHALE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> COPPER_GLOVE = REGISTRY.register("copper_glove", () -> new CopperGloveItem());
	public static final RegistryObject<Item> SHRIMP_SPAWN_EGG = REGISTRY.register("shrimp_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.SHRIMP, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MMA_GLOVE = REGISTRY.register("mma_glove", () -> new MMAGloveItem());
	public static final RegistryObject<Item> WITHER_RING = REGISTRY.register("wither_ring", () -> new WitherRingItem());
	public static final RegistryObject<Item> RING = REGISTRY.register("ring", () -> new RingItem());
	public static final RegistryObject<Item> FIRE_RING = REGISTRY.register("fire_ring", () -> new FireRingItem());
	public static final RegistryObject<Item> POISON_RING = REGISTRY.register("poison_ring", () -> new PoisonRingItem());
	public static final RegistryObject<Item> PIGLIN_BOULUS_SPAWN_EGG = REGISTRY.register("piglin_boulus_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.PIGLIN_BOULUS, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PIGLIN_BOXER_SPAWN_EGG = REGISTRY.register("piglin_boxer_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.PIGLIN_BOXER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SHRIMP_DEATH = REGISTRY.register("shrimp_death", () -> new ShrimpDeathItem());
	public static final RegistryObject<Item> RAW_SHRIMP = REGISTRY.register("raw_shrimp", () -> new RawShrimpItem());
	public static final RegistryObject<Item> COOKED_SHRIMP = REGISTRY.register("cooked_shrimp", () -> new CookedShrimpItem());
	public static final RegistryObject<Item> ARCHDUKE_LYTHERION_SPAWN_EGG = REGISTRY.register("archduke_lytherion_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.ARCHDUKE_LYTHERION, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> CORIUM = block(MorebossesModBlocks.CORIUM);
	public static final RegistryObject<Item> BLOLIUM = block(MorebossesModBlocks.BLOLIUM);
	public static final RegistryObject<Item> OPAL_ORE_IN_DOOM_ROCK = block(MorebossesModBlocks.OPAL_ORE_IN_DOOM_ROCK);
	public static final RegistryObject<Item> OPAL = REGISTRY.register("opal", () -> new OpalItem());
	public static final RegistryObject<Item> MAGMATIC_CHAMPION_SPAWN_EGG = REGISTRY.register("magmatic_champion_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.MAGMATIC_CHAMPION, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> HELLISH_TUNGSTEN_INGOT = REGISTRY.register("hellish_tungsten_ingot", () -> new HellishTungstenIngotItem());
	public static final RegistryObject<Item> HELLISH_TUNGSTEN_BLOCK = block(MorebossesModBlocks.HELLISH_TUNGSTEN_BLOCK);
	public static final RegistryObject<Item> DOOM_ROCK = block(MorebossesModBlocks.DOOM_ROCK);
	public static final RegistryObject<Item> OPAL_ORE_IN_CORIUM = block(MorebossesModBlocks.OPAL_ORE_IN_CORIUM);
	public static final RegistryObject<Item> COBBLED_DOOM_ROCK = block(MorebossesModBlocks.COBBLED_DOOM_ROCK);
	public static final RegistryObject<Item> BOB_BUCKET = REGISTRY.register("bob_bucket", () -> new BobItem());
	public static final RegistryObject<Item> COPPER_DISC = REGISTRY.register("copper_disc", () -> new CopperDiscItem());
	public static final RegistryObject<Item> JUNGLE_ESSENCE = REGISTRY.register("jungle_essence", () -> new JungleEssenceItem());
	public static final RegistryObject<Item> ARMAGEDOM = REGISTRY.register("armagedom", () -> new ArmagedomItem());
	public static final RegistryObject<Item> BASALTIC_SHARD = REGISTRY.register("basaltic_shard", () -> new BasalticShardItem());
	public static final RegistryObject<Item> COLOSSEUM_BRICKS = block(MorebossesModBlocks.COLOSSEUM_BRICKS);
	public static final RegistryObject<Item> COLOSSEUM_BRICKS_FENCE = block(MorebossesModBlocks.COLOSSEUM_BRICKS_FENCE);
	public static final RegistryObject<Item> COLOSSEUM_BRICKS_WALL = block(MorebossesModBlocks.COLOSSEUM_BRICKS_WALL);
	public static final RegistryObject<Item> COLOSSEUM_BRICKS_SLAB = block(MorebossesModBlocks.COLOSSEUM_BRICKS_SLAB);
	public static final RegistryObject<Item> COLOSSEUM_BRICKS_STAIRS = block(MorebossesModBlocks.COLOSSEUM_BRICKS_STAIRS);
	public static final RegistryObject<Item> SHINING_COLOSSEUM_BRICKS = block(MorebossesModBlocks.SHINING_COLOSSEUM_BRICKS);
	public static final RegistryObject<Item> BASALTIC_SHIELD = REGISTRY.register("basaltic_shield", () -> new BasalticShieldItem());
	public static final RegistryObject<Item> STROKE = block(MorebossesModBlocks.STROKE);
	public static final RegistryObject<Item> STRIKE = block(MorebossesModBlocks.STRIKE);
	public static final RegistryObject<Item> COARSE = block(MorebossesModBlocks.COARSE);
	public static final RegistryObject<Item> BROKEN_SWORD = REGISTRY.register("broken_sword", () -> new BrokenSwordItem());
	public static final RegistryObject<Item> NETHERITE_LONG_SWORD = REGISTRY.register("netherite_long_sword", () -> new NetheriteLongSwordItem());
	public static final RegistryObject<Item> STROKE_MELON = block(MorebossesModBlocks.STROKE_MELON);
	public static final RegistryObject<Item> CARVED_STROKE_MELON = block(MorebossesModBlocks.CARVED_STROKE_MELON);
	public static final RegistryObject<Item> JACK_O_STROKE = block(MorebossesModBlocks.JACK_O_STROKE);
	public static final RegistryObject<Item> STROKE_NEST = block(MorebossesModBlocks.STROKE_NEST);
	public static final RegistryObject<Item> STROKE_GRASS = block(MorebossesModBlocks.STROKE_GRASS);
	public static final RegistryObject<Item> BLOMI_BERRY = REGISTRY.register("blomi_berry", () -> new BlomiBerryItem());
	public static final RegistryObject<Item> BLOMI_BERRY_BUSH = block(MorebossesModBlocks.BLOMI_BERRY_BUSH);
	public static final RegistryObject<Item> BLOMI_BERRY_SEEDS = REGISTRY.register("blomi_berry_seeds", () -> new BlomiBerrySeedsItem());
	public static final RegistryObject<Item> DIAMONDED_BLOMI_BERRY = REGISTRY.register("diamonded_blomi_berry", () -> new DiamondedBlomiBerryItem());
	public static final RegistryObject<Item> SLAGTIO_THE_MIGHTY_SPAWN_EGG = REGISTRY.register("slagtio_the_mighty_spawn_egg", () -> new ForgeSpawnEggItem(MorebossesModEntities.SLAGTIO_THE_MIGHTY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BROKEN_IDOL = REGISTRY.register("broken_idol", () -> new BrokenIdolItem());
	public static final RegistryObject<Item> WOODRITE_INGOT = REGISTRY.register("woodrite_ingot", () -> new WoodriteIngotItem());
	public static final RegistryObject<Item> LUSH_EYE = REGISTRY.register("lush_eye", () -> new LushEyeItem());
	public static final RegistryObject<Item> OLD_EYE = REGISTRY.register("old_eye", () -> new OldEyeItem());
	public static final RegistryObject<Item> SDB = block(MorebossesModBlocks.SDB);
	public static final RegistryObject<Item> OLD_STEEL_INGOT = REGISTRY.register("old_steel_ingot", () -> new OldSteelIngotItem());
	public static final RegistryObject<Item> THE_LIFE_ENDER = REGISTRY.register("the_life_ender", () -> new TheLifeEnderItem());
	public static final RegistryObject<Item> OLD_STEEL_SMITHING_UPGRADE = REGISTRY.register("old_steel_smithing_upgrade", () -> new OldSteelSmithingUpgradeItem());
	public static final RegistryObject<Item> BOSS_REMOVER = REGISTRY.register("boss_remover", () -> new BossRemoverItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(BASALTIC_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
		});
	}
}
